spring.datasource.url=jdbc:postgresql://localhost:5433/medico_db?useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=postgres
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

app.jwt.secret=CHANGE_ME_SUPER_SECRET_256_BIT_KEY
app.jwt.expiration-ms=86400000

app.otp.delivery=EMAIL
app.otp.expiration-minutes=5
app.consent.validity-minutes=1440

app.storage.type=LOCAL
app.upload.dir=uploads
app.base-url=http://localhost:8080

# Email OTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cloudmedico0@gmail.com
spring.mail.password=${GMAIL_APP_PASSWORD:gnpkmzdfnejbmnsl}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ML Microservice
ml.service.url=http://localhost:5000

# Gemini Lifestyle Chat
ai.gemini.api-key=${GEMINI_API_KEY:}
ai.gemini.model=gemini-1.5-flash

# File upload limits
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=25MB
